controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController

    left_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController

    right_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController

left_wheel_velocity_controller:
  ros__parameters:
    joint: wheel_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

right_wheel_velocity_controller:
  ros__parameters:
    joint: wheel_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}