<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="my_robot">

  <!-- Parameters -->
  <xacro:property name="base_size" value="0.5 0.5 0.2"/>
  <xacro:property name="arm_radius" value="0.05"/>
  <xacro:property name="arm_length" value="0.6"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_size}"/>
      </geometry>
      <origin xyz="0 0 ${0.5 * 0.2}"/>
      <material name="gray">
      </material>
    </visual>
  </link>

  <!-- Fixed Joint: base_link -> arm_link -->
  <!-- <joint name="base_to_arm" type="revolute">
    <parent link="base_link"/>
    <child link="arm_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="1.0"/>
  </joint> -->

  <joint name="base_to_arm" type="revolute">
        <parent link="base_link"/>
        <child link="arm_link"/>
        <origin xyz="0.25 0 0.15" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>


  <!-- Arm Link -->
  <link name="arm_link">
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <!-- <origin xyz="0 0 ${arm_length / 2}"/> -->
      <origin xyz="${arm_length / 2} 0 0" rpy="0 ${pi/2} 0"/>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
  </link>

</robot>
